CREATE TABLE ACCOUNT_ROLE (
  ACCOUNT_ID BIGINT NOT NULL,
  ROLE_ID BIGINT NOT NULL
);

ALTER TABLE ACCOUNT_ROLE
  ADD CONSTRAINT FK_ACCOUNT_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT;
ALTER TABLE ACCOUNT_ROLE
  ADD CONSTRAINT FK_ROLE_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE;