ALTER TABLE ACCOUNT ALTER COLUMN LOGIN TYPE VARCHAR(100);
ALTER TABLE ACCOUNT ALTER COLUMN PASSWORD TYPE VARCHAR(100);
ALTER TABLE ACCOUNT ALTER COLUMN FIRSTNAME TYPE VARCHAR(100);
ALTER TABLE ACCOUNT ALTER COLUMN LASTNAME TYPE VARCHAR(150);
